config/routes.rb
Rails.application.routes.draw do
  get 'public_recipes/index'
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, except: :show
  get 'users/:id', to: 'users#show', as: :user_show, constraints: { id: /\d+/ }
  
  resources :recipes do
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]

    patch 'toggle_public', on: :member
  end
  
  authenticated :user do
    root 'public_recipes#index', as: :authenticated_root
  end

  unauthenticated :user do
    root 'public_recipes#index', as: :unauthenticated_root
  end

  resources :foods

  get 'shopping_list' => 'shopping_lists#index', as: :shopping_list

  get "up" => "rails/health#show", as: :rails_health_check

  root "public_recipes#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :steps, dependent: :destroy
  has_many :recipe_foods, dependent: :destroy, counter_cache: true
  has_many :foods, through: :recipe_foods
  accepts_nested_attributes_for :recipe_foods, allow_destroy: true
  accepts_nested_attributes_for :steps, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true
  validates :preparation_time, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :cooking_time, presence: true
  validates :description, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  # GET /recipes or /recipes.json
  def index
    # @recipes = Recipe.all
    @recipes = current_user.recipes
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
    authorize! :read, @recipe
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @recipe.steps.build # Build an empty step for the form
    @user = current_user
  end

  # GET /recipes/1/edit
  def edit; end

  def create
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])

    # Check if the current user is the owner of the recipe
    if @recipe.user == current_user
      @recipe.recipe_foods.destroy_all
      @recipe.destroy
      redirect_to recipes_path, notice: 'Recipe eliminated successfully.'
    else
      # If the current user is not the owner, handle unauthorized access
      redirect_to recipes_path, alert: 'You are not authorized to delete this recipe.'
    end
  end

  def add_ingredient
    @recipe = Recipe.find(params[:id])
    @food = Food.new
    @foods = Food.all
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.toggle!(:public)
    respond_to do |format|
      format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
      format.json { render :show, status: :ok, location: @recipe }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public,
                                   steps_attributes: %i[description _destroy])
  end

  def food_params
    params.require(:food).permit(:name, :price, :measurement_unit)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, class: 'my-4') do |form| %>
  <% if recipe.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, style: "display: block", class: "fw-bold form-label" %>
    <%= form.text_field :name, class: "form-control", placeholder: "Recipe Name" %>
  </div>

  <div class="mb-3">
    <%= form.label :preparation_time, style: "display: block", class: "fw-bold form-label" %>
    <%= form.text_field :preparation_time, class: "form-control", placeholder: "Preparation time" %>
  </div>

  <div class="mb-3">
    <%= form.label :cooking_time, style: "display: block", class: "fw-bold form-label" %>
    <%= form.text_field :cooking_time, class: "form-control", placeholder: "Cooking time" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, style: "display: block", class: "fw-bold form-label" %>
    <%= form.text_area :description, class: "form-control", placeholder: "Description" %>
  </div>

  <div class="mb-3">
    <%= form.label :public, class: "fw-bold form-label me-3" %>
    <%= form.check_box :public, class: "form-check-input" %>
  </div>

  <!-- Nested form for steps -->
  <div class="mb-3">
    <%= form.fields_for :steps do |step_form| %>
      <%= step_form.label :description, style: "display: block", class: "fw-bold form-label" %>
      <%= step_form.text_area :description, class: "form-control", placeholder: "Enter step description" %>
      <%= step_form.check_box :_destroy, class: "form-check-input" %>
      <%= step_form.label :_destroy, class: "fw-bold form-check-label", style: "display: inline-block; margin-left: 5px" do %>
        Remove Step
      <% end %>
    <% end %>
  </div>
  <div>
    <%= form.submit class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <div class="d-flex justify-content-center">
    <h1>
      <%= recipe.name %>
    </h1>
  </div>

  <div class="toggle_public">
    <% if user_signed_in? && current_user.id == recipe.user_id %>
      <div class="d-flex justify-content-end form-check form-switch" style="display: flex;">
        <%= form_for recipe, url: toggle_public_recipe_path(recipe.id), method: :patch, html: { class: 'd-flex flex-row align-items-center' } do |form| %>
          <label class="form-check-label mx-5" for="<%= dom_id(recipe, :public) %>">Public</label>
          <%= form.check_box :public, class: "form-check-input", id: dom_id(recipe, :public), onchange: "this.form.submit()" %>
        <% end %>

      </div>

  <% end %>
  </div>

  <p>
  <strong>Preparation Time:</strong>

    <%= recipe.preparation_time %> <%= "hour".pluralize(@recipe.preparation_time) %>
  </p>

  <p>
    <strong>Cooking time:</strong>
    <%= recipe.cooking_time %> <%= "hour".pluralize(@recipe.cooking_time) %>
  </p>

  <h2>Steps:</h2>
  <% @recipe.steps.each do |step| %>
    <p><%= step.description %></p>
  <% end %>


</div>

app/views/recipes/add_ingredient.html.erb
<!-- app/views/recipes/add_ingredient.html.erb -->

<!--<h3>Add Ingredient</h3>-->
<%#= form_with(model: @food, url: save_ingredient_recipe_path(@recipe), local: true) do |form| %>
<!--  <div class="mb-3">-->
    <%#= form.label :food_id, class: "fw-bold form-label" %>
    <%#= form.collection_select :food_id, @foods, :id, :name, prompt: 'Select a food' %>
<!--  </div>-->

<!--  <div class="mb-3">-->
    <%#= form.label :quantity, class: "fw-bold form-label" %>
    <%#= form.number_field :quantity, class: "form-control", placeholder: "Quantity" %>
<!--  </div>-->

<!--  <div>-->
    <%#= form.submit "Add Ingredient", class: 'btn btn-primary' %>
<!--  </div>-->
<%# end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<div class="col-md-10">

<%= link_to 'Add Recipe', new_recipe_path, class: 'btn btn-primary float-end' %>
<h2>List of Recipes</h2>

  <% @recipes.each do |recipe| %>
    <div class="border p-4 mb-2">
      <h2><%= link_to recipe.name, recipe_path(recipe) %></h2>
      <p><%= recipe.description %></p>
      <%= button_to 'Remove', recipe_path(recipe.id), method: :delete, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, class: 'btn btn-danger btn-sm' %>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe %>

<div>
  <div class="d-flex justify-content-between">
  
      <%= link_to 'Generate Shopping List', shopping_list_path , class: 'btn btn-primary float-end mb-5' %>
 
    <%= link_to "Add ingredients", new_recipe_recipe_food_path(@recipe), class: 'btn btn-primary float-end mb-5' %>
  </div>

  <h3>Ingredients</h3>

  <table class="table container rounded">
    <thead>
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Quantity</th>
      <th scope="col">Value</th>
      <th scope="col"></th>
    </tr>
    </thead>
    <tbody>

    <!-- Hidden row for the first empty ingredient -->
    <tr id="emptyRow" style="display: none;">
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>

    <% @recipe.recipe_foods.each_with_index do |recipeFood, index| %>
      <tr>
        <td><%= recipeFood.food.name %></td>
        <td><%= recipeFood.quantity %><%= recipeFood.food.measurment_unit  %></td>
        <td>$<%= recipeFood.quantity * recipeFood.food.price %></td>
        <td class="d-flex gap-3 justify-content-end">
          <% if can? :destroy, @recipe %>
            <%= button_to "Delete", recipe_recipe_food_path(@recipe, recipeFood), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" } %>
            <%= link_to "Modify", edit_recipe_recipe_food_path(recipe_id: @recipe.id, id: recipeFood.id), class:"btn btn-dark" %>
          <% end %>
        </td>
      </tr>
    <% end %>

    </tbody>
  </table>

  <div>
    <%= link_to 'Back to Recipes', recipes_path, class: 'btn btn-secondary' %>
  </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        // Add ingredient button click event
        document.getElementById("addIngredientBtn").addEventListener("click", function() {
            // Show the hidden row (first empty ingredient)
            document.getElementById("emptyRow").style.display = "table-row";
        });
    });
</script>