config/routes.rb
Rails.application.routes.draw do
  get 'public_recipes/index'
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, except: :show
  get 'users/:id', to: 'users#show', as: :user_show, constraints: { id: /\d+/ }
  
  resources :recipes do
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]

    patch 'toggle_public', on: :member
  end
  
  authenticated :user do
    root 'public_recipes#index', as: :authenticated_root
  end

  unauthenticated :user do
    root 'public_recipes#index', as: :unauthenticated_root
  end

  resources :foods

  get 'shopping_list' => 'shopping_lists#index', as: :shopping_list

  get "up" => "rails/health#show", as: :rails_health_check

  root "public_recipes#index"
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true
  validates :measurment_unit, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = current_user.foods
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)

    # Set the user_id from the current_user
    @food.user_id = current_user.id if user_signed_in?

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_url, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    # Ensure that only the owner can delete the food
    if @food.user == current_user
      @food.destroy
      respond_to do |format|
        format.html { redirect_to foods_url, notice: 'Food was successfully deleted.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to foods_url, alert: 'You are not authorized to delete this food.' }
        format.json { render json: { error: 'Unauthorized' }, status: :unauthorized }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurment_unit, :price, :quantity, :user_id)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>

  <p>
    <strong>Measurment unit:</strong>
    <%= food.measurment_unit %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= food.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= food.quantity %>
  </p>

  <p>
    <strong>User:</strong>
    <%= food.user_id %>
  </p>

</div>

app/views/foods/_form.html.erb
<%= form_with(model: food, class: "needs-validation", novalidate: true) do |form| %>
  <% if food.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :measurment_unit, class: "form-label" %>
    <%= form.text_field :measurment_unit, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :price, class: "form-label" %>
    <%= form.text_field :price, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :quantity, class: "form-label" %>
    <%= form.number_field :quantity, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="d-flex justify-content-end mb-4">
  <%= link_to "Add food", new_food_path, class: "btn btn-success" %>
</div>

<table class="table">
  <thead>
  <tr>
    <th scope="col" class="d-none">ID</th>
    <th scope="col">Name</th>
    <th scope="col">Measurement Unit</th>
    <th scope="col">Price</th>
    <th scope="col">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @foods.each do |food| %>
    <tr>
      <th scope="row" class="d-none"><%= food.id %></th>
      <td><%= food.name %></td>
      <td><%= food.measurment_unit %></td>
      <td><%= food.price %></td>
      <td>
        <%= button_to "Delete", food, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>