config/routes.rb
Rails.application.routes.draw do
  get 'public_recipes/index'
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, except: :show
  get 'users/:id', to: 'users#show', as: :user_show, constraints: { id: /\d+/ }
  
  resources :recipes do
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]

    patch 'toggle_public', on: :member
  end
  
  authenticated :user do
    root 'public_recipes#index', as: :authenticated_root
  end

  unauthenticated :user do
    root 'public_recipes#index', as: :unauthenticated_root
  end

  resources :foods

  get 'shopping_list' => 'shopping_lists#index', as: :shopping_list

  get "up" => "rails/health#show", as: :rails_health_check

  root "public_recipes#index"
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe, counter_cache: true
  belongs_to :food

  validates :quantity, presence: true
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_food, only: [:update]

  def new
    @recipe_food = RecipeFood.new
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.recipe_id = params[:recipe_id]
    if @recipe_food.save
      redirect_to recipe_path(params[:recipe_id]), notice: 'Ingredient was successfully added.'
    else
      render :new
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    redirect_to recipe_path(@recipe_food.recipe), notice: 'Ingredient was successfully removed.'
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:recipe_id])

    respond_to do |format|
      if @recipe_food.update(recipe_food_params)
        format.html do
          redirect_to recipe_recipe_food_url(@recipe, @recipe_food), notice: 'Recipe food was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @recipe_food }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/_recipe_food.html.erb
<div id="<%= dom_id recipe_food %>">
  <p>
    <strong>Quantity:</strong>
    <%= recipe_food.quantity %>
  </p>

  <p>
    <strong>Recipe:</strong>
    <%= recipe_food.recipe_id %>
  </p>

  <p>
    <strong>Food:</strong>
    <%= recipe_food.food_id %>
  </p>

</div>

app/views/recipe_foods/edit.html.erb
<div class="col-md-6">
<h2>Edit Ingredient</h2>
<hr class="border border-primary border-2 opacity-50">
<%= form_with(model: @recipe_food, method: :patch, url: recipe_recipe_food_path, local: true) do |form| %>

  <div class="mb-3">
    <%= form.label :quantity, style: "display: block",class: "fw-bold form-label" %>
    <%= form.number_field :quantity, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :food_id, style: "display: block",class: "fw-bold form-label" %>
     <%= form.collection_select :food_id, current_user.foods, :id, :name, { include_blank: false }, class: 'form-control' %>
  </div>

   <div class="mb-3">
    <%= form.submit "Update", class: 'btn btn-primary' %>
  </div>

<% end %>
</div>

app/views/recipe_foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipe foods</h1>

<div id="recipe_foods">
  <% @recipe_foods.each do |recipe_food| %>
    <%= render recipe_food %>
    <p>
      <%= link_to "Show this recipe food", recipe_food %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe food", new_recipe_food_path %>

app/views/recipe_foods/new.html.erb
<div class="col-md-6">
<h2>Add New Ingredient</h2>
<hr class="border border-primary border-2 opacity-50">
<%= form_with(model: @recipe_food, url: recipe_recipe_foods_path, local: true) do |form| %>

  <div class="mb-3">
    <%= form.label :quantity, style: "display: block",class: "fw-bold form-label" %>
    <%= form.number_field :quantity, class: "form-control", value: 1 %>
  </div>

  <div class="mb-3">
    <%= form.label :food_id, style: "display: block",class: "fw-bold form-label" %>
     <%= form.collection_select :food_id, current_user.foods, :id, :name, { include_blank: false }, class: 'form-control' %>
  </div>

   <div class="mb-3">
    <%= form.submit "Create Ingredient", class: 'btn btn-primary' %>
  </div>

<% end %>
</div>